name: Docker Image CI

on: 
  release:
    types: [created, edited]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Export Tag Name
      run: echo "NEW_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag virtaltd/pipeline-aws-terragrunt:${{ env.NEW_TAG }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Push
      run: docker push virtaltd/pipeline-aws-terragrunt:${{ env.NEW_TAG }}
    - name: Docker Tag Latest
      run: docker tag virtaltd/pipeline-aws-terragrunt:${{ env.NEW_TAG }} virtaltd/pipeline-aws-terragrunt:latest
    - name: Docker Tag Latest Push
      run: docker push virtaltd/pipeline-aws-terragrunt:latest
